# Generated by Django 4.2.7 on 2023-12-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='bg.png', null=True, upload_to=''),
        ),
    ]
